USE [Medilab]
GO

INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),1,'Examen Ingreso Mínimo De Ley','Examen Ingreso Mínimo De Ley',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),8,'Examen Ingreso Completo  ','Examen Ingreso Completo  ',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),11,'Examen Periódico Completo','Examen Periódico Completo',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),21,'Carnet De Conducir (Paquete)','Carnet De Conducir (Paquete)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),37,'Examen Egreso  Completo','Examen Egreso  Completo',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),41,'Examen Periódico Mínimo De Ley','Examen Periódico Mínimo De Ley',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),42,'Libreta  Sanitaria','Libreta  Sanitaria',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),43,'Examen Egreso Mínimo De Ley','Examen Egreso Mínimo De Ley',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),52,'Examen Periódico Mínimo De Ley (Sin Rx)','Examen Periódico Mínimo De Ley (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),64,'Examen Mínimo De Ley (Sin  Rx)','Examen Mínimo De Ley (Sin  Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),119,'Examen Ingreso Mínimo De Ley  (Sin Rx)','Examen Ingreso Mínimo De Ley  (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),209,'Examen Egreso Completo (Sin Rx)','Examen Egreso Completo (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),266,'Libreta Sanitaria (Sin Rx Torax)','Libreta Sanitaria (Sin Rx Torax)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),305,'Exam. Egreso Mín. Ley  (Sin Rx)','Exam. Egreso Mín. Ley  (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),344,'Examenes Periódicos De Telecom','Examenes Periódicos De Telecom',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),345,'Exámenes De Egreso Telecom','Exámenes De Egreso Telecom',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),347,'Preocupacional De Ingreso Telecom','Preocupacional De Ingreso Telecom',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),412,'Paquetes De Drogas','Paquetes De Drogas',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),419,'Ex. Ingreso M De Ley + Col F/P','Ex. Ingreso M De Ley + Col F/P',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),427,'Item 1 Examen Medicos Pre-Ingreso','Item 1 Examen Medicos Pre-Ingreso',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),432,'Item 1 Exámen Básico Completo','Item 1 Exámen Básico Completo',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),445,'Estudio Complementario 187','Estudio Complementario 187',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),446,'Estudio Complementario 188','Estudio Complementario 188',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),447,'Exam. Ingreso Completo (Sin Rx)','Exam. Ingreso Completo (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),537,'Visado De Carnet','Visado De Carnet',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),604,'Exam. Periódico Completo (Sin Rx)','Exam. Periódico Completo (Sin Rx)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),638,'Enfermedad Prolongada (Completo)','Enfermedad Prolongada (Completo)',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),640,'Examen Ingreso Completo Con Placas','Examen Ingreso Completo Con Placas',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),641,'Examen Básico De Ley Con Placas ','Examen Básico De Ley Con Placas ',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),646,'Examen Periódico Completo Con Placas','Examen Periódico Completo Con Placas',0)
INSERT INTO [dbo].[Group] (GroupId,GroupCode,GroupName,GroupDescription,IsDeleted) VALUES (NEWID(),678,'Examen Egreso Ecogas','Examen Egreso Ecogas',0)
GO