//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medilab.UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medilab.UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examenes completos.
        /// </summary>
        internal static string AllExamsCompleted {
            get {
                return ResourceManager.GetString("AllExamsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia clínica completa. El paciente debe pasar a firmar la declaracion jurada por la recepcion..
        /// </summary>
        internal static string ClinicalHistoryCompleted {
            get {
                return ResourceManager.GetString("ClinicalHistoryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia Clinica Guardada.
        /// </summary>
        internal static string ClinicalHistorySaved {
            get {
                return ResourceManager.GetString("ClinicalHistorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe ser único.
        /// </summary>
        internal static string CodeMustBeUnique {
            get {
                return ResourceManager.GetString("CodeMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar eliminacion.
        /// </summary>
        internal static string ConfirmationDialogDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmationDialogDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CUIT debe ser único..
        /// </summary>
        internal static string CuitMustBeUnique {
            get {
                return ResourceManager.GetString("CuitMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación guardada.
        /// </summary>
        internal static string HistoryEvaluatedMessage {
            get {
                return ResourceManager.GetString("HistoryEvaluatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación.
        /// </summary>
        internal static string HistoryEvaluatedTitle {
            get {
                return ResourceManager.GetString("HistoryEvaluatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados guardados.
        /// </summary>
        internal static string HistoryResultSavedMessage {
            get {
                return ResourceManager.GetString("HistoryResultSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        internal static string HistoryResultSavedTitle {
            get {
                return ResourceManager.GetString("HistoryResultSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files(*.BMP;*.JPG;*.GIF;*.PNG)|*.BMP;*.JPG;*.GIF;*.PNG|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFileExtensionList {
            get {
                return ResourceManager.GetString("ImageFileExtensionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o clave no valida.
        /// </summary>
        internal static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mainIcon {
            get {
                object obj = ResourceManager.GetObject("mainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo usuario.
        /// </summary>
        internal static string NewUserText {
            get {
                return ResourceManager.GetString("NewUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna configuracion de empresa activada. Por favor cree y active una o active una de las creadas..
        /// </summary>
        internal static string NoActiveConfigurationErrorText {
            get {
                return ResourceManager.GetString("NoActiveConfigurationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disponible.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número debe ser único..
        /// </summary>
        internal static string NumberMustBeUnique {
            get {
                return ResourceManager.GetString("NumberMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una o mas facturas pendientes de impresión. Debe imprimir primero la factura numero {0}. .
        /// </summary>
        internal static string PendingInvoiceToPrintError {
            get {
                return ResourceManager.GetString("PendingInvoiceToPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente:.
        /// </summary>
        internal static string PracticeByClientReportName {
            get {
                return ResourceManager.GetString("PracticeByClientReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte: Prácticas por Cliente.
        /// </summary>
        internal static string PracticeByClientReportTitle {
            get {
                return ResourceManager.GetString("PracticeByClientReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro que desea elimiar el registro seleccionado?.
        /// </summary>
        internal static string QuestionDeleteRecordText {
            get {
                return ResourceManager.GetString("QuestionDeleteRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro que desea anular la factura N° {0}? Esta operación no podrá ser revertida..
        /// </summary>
        internal static string QuestionDisableInvoiceText {
            get {
                return ResourceManager.GetString("QuestionDisableInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar anulación..
        /// </summary>
        internal static string QuestionDisableInvoiceTitle {
            get {
                return ResourceManager.GetString("QuestionDisableInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro no entontrado.
        /// </summary>
        internal static string RecordNotFoundErrorText {
            get {
                return ResourceManager.GetString("RecordNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos una práctica.
        /// </summary>
        internal static string SelectAtLeastOnePractice {
            get {
                return ResourceManager.GetString("SelectAtLeastOnePractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una provincia..
        /// </summary>
        internal static string SelectAtLeastOneState {
            get {
                return ResourceManager.GetString("SelectAtLeastOneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string StatusFilterAll {
            get {
                return ResourceManager.GetString("StatusFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pagado:.
        /// </summary>
        internal static string TotalPagado {
            get {
                return ResourceManager.GetString("TotalPagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe. Por favor seleccione otro..
        /// </summary>
        internal static string UserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comprobante fue generado correctamente..
        /// </summary>
        internal static string VoucherSaveSuccesfulyText {
            get {
                return ResourceManager.GetString("VoucherSaveSuccesfulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto..
        /// </summary>
        internal static string VoucherSaveSuccesfulyTitle {
            get {
                return ResourceManager.GetString("VoucherSaveSuccesfulyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
